// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QulificationToolForCreditCard.Models;

namespace QulificationToolForCreditCard.Migrations
{
    [DbContext(typeof(CreditCardContext))]
    [Migration("20200706183526_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QulificationToolForCreditCard.Models.CardDetails", b =>
                {
                    b.Property<int>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardName")
                        .HasColumnName("nvarchar(50");

                    b.Property<string>("Message")
                        .HasColumnName("nvarchar(50");

                    b.HasKey("CreditCardId");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("QulificationToolForCreditCard.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnName("Annual_Income");

                    b.Property<int>("CreditCardId");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("nvarchar(50");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("nvarchar(50");

                    b.HasKey("CustomerId");

                    b.HasIndex("CreditCardId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("QulificationToolForCreditCard.Models.Customer", b =>
                {
                    b.HasOne("QulificationToolForCreditCard.Models.CardDetails", "CardDetails")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
