// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QulificationToolForCreditCard.Models;

namespace QulificationToolForCreditCard.Migrations
{
    [DbContext(typeof(CreditCardContext))]
    [Migration("20200706213729_updatedColumnDetailsAndSeed")]
    partial class updatedColumnDetailsAndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QulificationToolForCreditCard.Models.CardDetails", b =>
                {
                    b.Property<int>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("APR");

                    b.Property<string>("CardName")
                        .HasMaxLength(50);

                    b.Property<string>("Message");

                    b.HasKey("CreditCardId");

                    b.ToTable("CardDetails");

                    b.HasData(
                        new { CreditCardId = 1, APR = 0m, CardName = "None", Message = "No credit cards are available" },
                        new { CreditCardId = 2, APR = 24.6m, CardName = "Barclay", Message = "Enjoy the Barclay credit card" },
                        new { CreditCardId = 3, APR = 36.8m, CardName = "Vanquis", Message = "Enjoy the Vanquis credit card" }
                    );
                });

            modelBuilder.Entity("QulificationToolForCreditCard.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnName("Annual_Income");

                    b.Property<int>("CreditCardId");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CustomerId");

                    b.HasIndex("CreditCardId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("QulificationToolForCreditCard.Models.Customer", b =>
                {
                    b.HasOne("QulificationToolForCreditCard.Models.CardDetails", "CardDetails")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
